codecov:
  token: 61281c00-6b96-40bc-9643-799a1d5280b9
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 10%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "docs/*"
  - "tests/*"
  - "*.md"
  - "setup.py"
  - "main.ipynb"
  - "media/*"

flags:
  unittests:
    paths:
      - rhoa/
    carryforward: true