name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history for Codecov accuracy

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests with coverage
        run: |
          pytest tests/ \
            --cov=rhoa \
            --cov-report=xml:coverage.xml \
            --cov-report=html \
            --cov-report=term-missing \
            --cov-branch \
            -v
          ls -la coverage.xml  # Debug check

      - name: Show commit SHA for debug
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          git rev-parse HEAD

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          verbose: true
          fail_ci_if_error: true
          commit_sha: ${{ github.sha }}
          branch: ${{ github.ref_name }}

