name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests with coverage
        run: |
          pytest tests/ \
            --cov=rhoa \
            --cov-report=xml:coverage.xml \
            --cov-report=html \
            --cov-report=term-missing \
            --cov-branch \
            -v
          ls -la coverage.xml  # Debug check

      - name: Upload coverage reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/
          retention-days: 30

      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        if: github.event_name == 'pull_request'
        with:
          pytest-xml-coverage-path: ./coverage.xml
          title: Coverage Report
          badge-title: Coverage

      - name: Report coverage to GitHub
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage.xml
          minimum_coverage: 70
          fail_below_threshold: false

